basePath: /v1
definitions:
  tools.ResponseData:
    properties:
      data:
        type: object
    type: object
  tools.ResponseError:
    properties:
      error:
        type: string
    type: object
  v1.PoolDetails:
    properties:
      active_stake:
        type: number
      address:
        type: string
      apr:
        type: number
      avg_score:
        type: integer
      avg_skipped_slots:
        type: number
      delinquent:
        type: number
      depossit_fee:
        type: number
      name:
        type: string
      rewards_fee:
        type: number
      tokens_supply:
        type: number
      unstake_liquidity:
        type: number
      validators:
        items:
          $ref: '#/definitions/v1.Validator'
        type: array
      withdrawal_fee:
        type: number
    type: object
  v1.TotalPoolsStatistic:
    properties:
      avg_performance_score:
        type: integer
      max_performance_score:
        type: integer
      min_performance_score:
        type: integer
      network_apy:
        type: number
      pools:
        type: integer
      skipped_slot:
        type: number
      total_active_stake:
        type: number
      total_active_stake_pool:
        type: number
      total_unstake_liquidity:
        type: number
      total_validators:
        type: integer
      usd:
        type: number
    type: object
  v1.Validator:
    properties:
      active_stake:
        type: number
      apy:
        type: number
      data_center:
        type: string
      fee:
        type: number
      node_pk:
        type: string
      score:
        type: integer
      skipped_slots:
        type: number
      vote_pk:
        type: string
    type: object
info:
  contact: {}
paths:
  /pool/{name}:
    get:
      consumes:
      - application/json
      description: get pool
      parameters:
      - description: Pool name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            allOf:
            - $ref: '#/definitions/tools.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/v1.PoolDetails'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/tools.ResponseError'
        "404":
          description: bad request
          schema:
            $ref: '#/definitions/tools.ResponseError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/tools.ResponseError'
        default:
          description: default response
          schema:
            $ref: '#/definitions/tools.ResponseError'
      summary: get pool
  /pools:
    get:
      consumes:
      - application/json
      description: get pools
      parameters:
      - default: 1
        description: offset for aggregation
        in: query
        name: offset
        required: true
        type: number
      - default: 10
        description: limit for aggregation
        in: query
        name: limit
        required: true
        type: number
      - description: stake-pool name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            allOf:
            - $ref: '#/definitions/tools.ResponseData'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.PoolDetails'
                  type: array
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/tools.ResponseError'
        "404":
          description: bad request
          schema:
            $ref: '#/definitions/tools.ResponseError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/tools.ResponseError'
        default:
          description: default response
          schema:
            $ref: '#/definitions/tools.ResponseError'
      summary: get pools
  /pools-statistic:
    get:
      consumes:
      - application/json
      description: get statistic
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            allOf:
            - $ref: '#/definitions/tools.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/v1.TotalPoolsStatistic'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/tools.ResponseError'
        "404":
          description: bad request
          schema:
            $ref: '#/definitions/tools.ResponseError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/tools.ResponseError'
        default:
          description: default response
          schema:
            $ref: '#/definitions/tools.ResponseError'
      summary: get statistic
swagger: "2.0"
